### ISSUE TITLE
Issue when creating a new route object locally

### ISSUE THREAD

**Issue by xens** [xens/ripeinator#1]
When creating a new route object locally that doesn't exists in the RIPEDB the script fails with the following error:

```
Traceback (most recent call last):
  File "/bin/ripe", line 280, in <module>
    ripe_create(args.db, pwd, json_output, key, type, args.dryrun)
  File "/bin/ripe", line 17, in ripe_create
    for i in object_entries:
NameError: global name 'object_entries' is not defined

```

**Comment by fischa** [comment]
I guess this issue is solved and can be closed?
